### ISSUE TITLE
TODOs from cardView

### ISSUE THREAD

**Issue by patrick-austin** [ral-facilities/datagateway#461]
**Description**:
There were a number of TODOs left in the cardView PR, and unticked boxes from #128 that might not have been addressed. They may vary in terms of importance, and some might not be actioned in the end. It may be easiest to create seperate issues as these are scoped/worked on?
- [x] **useMemo vs useEffect**: `datasetCardView` (but probably applies to multiple places). My understanding is useMemo triggers less renders, but I'm not sure what all the pros/cons are
- [ ] **Refactor add/remove buttons**: `datasetCardview` (but applies elsewhere). We have the same button defined in multiple places, would be more convenient to style it once and re-use by importing
- [x] **Duplicate count and data requests**: `cardView`. One of the "main items to fix", caused by multiple useEffects interfering with each other
- [x] **Filter panel selected items**: `cardView`. The card only filter panel starts "closed" even when filters are in effect due to re-rendering
- [x] **No results display**: `cardView`. When there are no results, we still display pagination, sort/filter panel
- [x] **Separate queries for card/table**: `dgcommon.reducer`. Card and table have distinct queries (i.e. filters and sorting), so the results and their order can be different between card/table view. This was intended in case the queries needed seperate handling, but it might be more intuitive to share sorting etc. between views.
- [x] **Advanced filters in small window**: from #128. Couldn't replicate this, but that might be due to pagination being set to both (or it could have been fixed already?)
- [x] **Rename filterTable to filterData**:  from #128. Both terms are used in the code, with the action `filterTable` being called via `pushPageFilter`, and `filterData` being the possibilities for the card only filtering in the state. It seems to work as is, so this could be an outdated comment?
- [ ] **Move elements to common**: from #128. Specifically `card` and `cardView`, related to #420. 
- [x] **Narrow window considerations**: from #128. When too narrow to display cards and filters/sorts side by side, the components should adjust to use the full width (lots of whitespace currently)
- [x] **UI while fetching**: from #128. Disable filters/sort/pagination/result # while fetching results?
- [x] **Query and browser navigation**: from #128. Navigating back/forwards using browser buttons doesn't apply the filters/sort from the url query (until manually refreshing).

**Acceptance criteria**:
- [x] Scope potential TODOs, and decide what's a priority

**Comment by patrick-austin** [comment]
- [ ] **Timing of of `fetchDownloadCart` in `pageContainer`**

Prior to cardView, this was called in `useEffect`, but when the container was changed to a Class, it was moved to `componentDidUpdate` with a comment saying it should be called on mount and a clause that ensures it is only ever called once (regardless of success). When manually testing it, the component updates ~3 times after mounting so `fetchDownloadCart` still occurs before the user interacts with anything, and is only called once. Practically, this is consistent with how it behaved before cardView as far as I can tell. It does however have the following flaws that I can see:
- If the fetch (silently) fails, we don't retry, so the cart will appear empty until we refresh the page or try to add to the cart (at which point it picks up any items in the cart already)
- If we change the cart state in another tab/window (i.e. via the download plugin) then the cart in dataview won't update until refreshing or adding/removing via dataview

I've left it as is for now, but might be worth into making the logic handle failed fetches better at least?

**Comment by patrick-austin** [comment]
- [ ] **Extend improvements to table view:** At the moment this would just be the inclusion of a message when filters exclude all data from being shown, but any other improvements made to CV should also be expanded to table view.
